feat(ci): [HARROW_6-3911] add JSON translations validation (#91)

diff --git a/.github/workflows/validate-translation-files.yml b/.github/workflows/validate-translation-files.yml
--- a/.github/workflows/validate-translation-files.yml
+++ b/.github/workflows/validate-translation-files.yml
@@ -1,19 +1,19 @@
-# Validate the po files to ensure translation files are compilable.
+# Validate translation files to ensure they are well-formed and conflict-free.
 
-name: Validate translation PO files
+name: Validate translation files
 
 on:
   - pull_request
 
 jobs:
   validate-po-files:
+    name: Validate PO files
     runs-on: ubuntu-latest
     permissions:
       contents: read
       pull-requests: write
     steps:
-      # Define .po filepaths, so we can skip this action unless a .po
-      # file has been modified in this diff
+      # Skip this job unless a .po file was modified in this diff
       - uses: dorny/paths-filter@v3
         id: filter
         with:
@@ -21,7 +21,6 @@ jobs:
             pofiles:
               - '**.po'
 
-      # Clones the openedx-translations repo
       - name: clone openedx/openedx-translations
         if: steps.filter.outputs.pofiles == 'true'
         uses: actions/checkout@v4
@@ -47,12 +46,12 @@ jobs:
           python --version
           make translations_scripts_requirements
 
-      - name: Validate translation files
-        id: validate_translation_files
+      - name: Validate PO translation files
+        id: validate_po_files
         if: steps.filter.outputs.pofiles == 'true'
         run: |
           has_validation_errors=0
-          python scripts/validate_translation_files.py 2>validation_errors.txt || has_validation_errors=1
+          python scripts/validate_translation_files.py --formats po 2>validation_errors.txt || has_validation_errors=1
           cat validation_errors.txt
 
           {
@@ -63,22 +62,90 @@ jobs:
 
           exit $has_validation_errors
 
-      - name: Post translation validation results as a comment
+      - name: Post PO validation results as a comment
         # Due to GitHub Actions security reasons posting a comment isn't possible on fork pull requests.
         # This shouldn't be an issue, because bots writes directly to this repository.
         if: ${{ always() && !github.event.pull_request.head.repo.fork }}
         uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc
         with:
           message: |
-            :white_check_mark: All translation files are valid.
+            :white_check_mark: All PO translation files are valid.
 
             This comment has been posted by the `validate-translation-files.yml` GitHub Actions workflow.
 
           message-failure: |
-            :warning: There are errors in the translation files:
+            :warning: There are errors in the PO translation files:
 
             ```
-            ${{ steps.validate_translation_files.outputs.VALIDATION_ERRORS || 'No errors were reported.' }}
+            ${{ steps.validate_po_files.outputs.VALIDATION_ERRORS || 'No errors were reported.' }}
+            ```
+
+            This comment has been posted by the `validate-translation-files.yml` GitHub Actions workflow.
+
+  validate-json-files:
+    name: Validate JSON files
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
+      pull-requests: write
+    steps:
+      # Skip this job unless a .json file was modified in this diff
+      - uses: dorny/paths-filter@v3
+        id: filter
+        with:
+          filters: |
+            jsonfiles:
+              - '**.json'
+
+      - name: clone openedx/openedx-translations
+        if: steps.filter.outputs.jsonfiles == 'true'
+        uses: actions/checkout@v4
+
+      - name: setup python
+        if: steps.filter.outputs.jsonfiles == 'true'
+        uses: actions/setup-python@v5
+        with:
+          python-version: '3.11'
+          cache: pip
+          cache-dependency-path: |
+            requirements/translations.txt
+
+      - name: Install requirements
+        if: steps.filter.outputs.jsonfiles == 'true'
+        run: |
+          python --version
+          make translations_scripts_requirements
+
+      - name: Validate JSON translation files
+        id: validate_json_files
+        if: steps.filter.outputs.jsonfiles == 'true'
+        run: |
+          has_validation_errors=0
+          python scripts/validate_translation_files.py --formats json 2>validation_errors.txt || has_validation_errors=1
+          cat validation_errors.txt
+
+          {
+            echo 'VALIDATION_ERRORS<<EOF'
+            fold -w 100 -s validation_errors.txt
+            echo EOF
+          } >> "$GITHUB_OUTPUT"
+
+          exit $has_validation_errors
+
+      - name: Post JSON validation results as a comment
+        if: ${{ always() && !github.event.pull_request.head.repo.fork }}
+        uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc
+        with:
+          message: |
+            :white_check_mark: All JSON translation files are valid.
+
+            This comment has been posted by the `validate-translation-files.yml` GitHub Actions workflow.
+
+          message-failure: |
+            :warning: There are errors in the JSON translation files:
+
+            ```
+            ${{ steps.validate_json_files.outputs.VALIDATION_ERRORS || 'No errors were reported.' }}
             ```
 
             This comment has been posted by the `validate-translation-files.yml` GitHub Actions workflow.
